### ISSUE TITLE
Sending direct message to user

### ISSUE THREAD

**Issue by arnoldtonderaimarunda** [pedrocarrico/slackly#1]
Hi @pedrocarrico 

Is Slackly able to send a direct message to a user instead of sending to a channel?

Many Thanks,

**Comment by pedrocarrico** [comment]
Hi @arnoldmarunda,

Yes it can send a direct message to a user instead of a channel.

Can you try it and report back and close this issue if it works?

Keep in mind that I haven't used or updated the gem in a while but I know others are using it on a daily basis.

Cheers!

**Comment by arnoldtonderaimarunda** [comment]
Thank for your response @pedrocarrico 
When I create the 'Incoming Webhook', it asks for a destination to post to i.e #channel or @user. I chose @slackbot as a placeholder.
I have tried to put the @amarunda in the code, of the user I would like to send a direct message as follows;
```
message_options = {
  text: 'Hello from Slackly',
  channel: '@amarunda'
}
s.message(message_options)
```
However, the message options above do not seem to override the default channel configured when setting up the 'incoming webhook' under Slack apps. It continues to send to @slackbot.

**Comment by pedrocarrico** [comment]
That is interesting...

At the moment I am unable to try and debug it further as I'm on vacation but if you're willing to dig deeper in the code and try to find the root cause and maybe submit a PR with a fix I would gladly accept it.

If not I'll try this out ASAP and reply here.

Many thanks!

**Comment by arnoldtonderaimarunda** [comment]
@pedrocarrico your gem works perfectly. 

My problem was that I had created the 'incoming webhook' as a Slack app.  
Slack API resources state the following;

> You cannot override the default username, icon, or channel for incoming webhooks attached to Slack apps. Instead, these values will stubbornly inherit from the associated Slack app configuration.

Once I deleted the Slack app, and created a standalone 'incoming webhook' everything works fine.

Greatly appreciate you responding whilst on vacation.

Many Thanks

**Comment by pedrocarrico** [comment]
Glad you found it @arnoldmarunda

Thank you for using slackly
